title: sarah8080tt's homepage
description: GitHub Pages example for promoting a project
github_username: sarah8080tt
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
